#!/bin/sh
#
#       /etc/rc.d/init.d/walls
#
#       Runs the SLOONG Walls Service.
#       
#
# chkconfig:   - 85 15 
#

### BEGIN INIT INFO
# Provides:          sloongnet
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sloongnet at boot time.
# Description:       Control sloongnet.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Default values

NAME=sloongnet
SLOONG_HOME=/prod/sloong
SLOONG_PATH=${SLOONG_HOME}/$NAME
SLOONG_USER=root
SERVICENAME="SLOONG Network Engine"
LOCKFILE=/var/lock/subsys/sloongnet
LOGPATH=${SLOONG_HOME}/log
LOGFILE=${LOGPATH}/sloongnet.log
RETVAL=0

# Don't do anything if nothing is installed
[ -x ${SLOONG_PATH} ] || exit 0
# exit if logpath dir is not created.
[ -x ${LOGPATH} ] || exit 0

DAEMON_OPTS="--check $NAME"

# Set additional options, if any
[ ! -z "$SLOONG_USER" ] && DAEMON_OPTS="$DAEMON_OPTS --user=${SLOONG_USER}"

start() {
  cd ${SLOONG_HOME}
  echo -n "Starting ${SERVICENAME}: "
  daemon $DAEMON_OPTS "${SLOONG_PATH} -r default.conf > ${LOGFILE} 2>&1 &"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch ${LOCKFILE}
        
  return $RETVAL
}

stop() {
  cd ${SLOONG_HOME}
        echo -n "Shutting down ${SERVICENAME}: "
        killproc ${NAME}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${LOCKFILE} 
}

case "$1" in
    start)
        status ${NAME} > /dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${NAME}
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL

