// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b2NvbC5wcm90bxIIUHJvdG9jb2wi3wEKC0RhdGFQYWNrYWdlEiUK",
            "CEZ1bmN0aW9uGAEgASgOMhMuUHJvdG9jb2wuRnVuY3Rpb25zEhUKDVByaW9y",
            "aXR5TGV2ZWwYAiABKAUSFAoMU2VyaWFsTnVtYmVyGAMgASgDEhMKC0NoZWNr",
            "U3RyaW5nGAQgASgJEg4KBlNlbmRlchgFIAEoCRIQCghSZWNlaXZlchgGIAEo",
            "BRIkCgZSZXN1bHQYByABKA4yFC5Qcm90b2NvbC5SZXN1bHRUeXBlEg8KB0Nv",
            "bnRlbnQYCCABKAkSDgoGRXh0ZW5kGAkgASgMIosDCg1HTE9CQUxfQ09ORklH",
            "EhIKCkxpc3RlblBvcnQYASABKAUSEQoJRW5hYmxlU1NMGAIgASgIEhQKDENl",
            "cnRGaWxlUGF0aBgDIAEoCRITCgtLZXlGaWxlUGF0aBgEIAEoCRISCgpDZXJ0",
            "UGFzc3dkGAUgASgJEhMKC0Nvbm5lY3RUaW1lGAYgASgFEhMKC1JlY2VpdmVU",
            "aW1lGAcgASgFEg8KB0xvZ1BhdGgYCCABKAkSJAoITG9nTGV2ZWwYCSABKA4y",
            "Ei5Qcm90b2NvbC5Mb2dMZXZlbBIRCglEZWJ1Z01vZGUYCiABKAgSGAoQTVFU",
            "aHJlYWRRdWFudGl0eRgLIAEoBRIbChNFUG9sbFRocmVhZFF1YW50aXR5GAwg",
            "ASgFEh0KFVByb2Nlc3NUaHJlYWRRdWFudGl0eRgNIAEoBRIUCgxQcmlvcml0",
            "eVNpemUYDiABKAUSIgoEVHlwZRgPIAEoDjIULlByb3RvY29sLk1vZHVsZVR5",
            "cGUSEAoIRXhDb25maWcYECABKAwiIwoOQ09OVFJPTF9DT05GSUcSEQoJQmxv",
            "Y2tUaW1lGAEgASgFImYKCURCX0NPTkZJRxIVCg1TZXJ2ZXJBZGRyZXNzGAEg",
            "ASgJEhIKClNlcnZlclBvcnQYAiABKAUSDAoEVXNlchgDIAEoCRIOCgZQYXNz",
            "d2QYBCABKAkSEAoIRGF0YWJhc2UYBSABKAkiPAoLREFUQV9DT05GSUcSFwoP",
            "RGF0YVJlY2VpdmVQb3J0GAEgASgFEhQKDERhdGFSZWN2VGltZRgCIAEoBSKM",
            "AQoOR0FURVdBWV9DT05GSUcSFwoPQ2xpZW50Q2hlY2tUaW1lGAEgASgFEhYK",
            "DkNsaWVudENoZWNrS2V5GAIgASgJEhwKFFRpbWVvdXRDaGVja0ludGVydmFs",
            "GAMgASgFEhMKC1RpbWVvdXRUaW1lGAQgASgFEhYKDlByb2Nlc3NBZGRyZXNz",
            "GAUgASgJIiQKD0ZJUkVXQUxMX0NPTkZJRxIRCglCbG9ja1RpbWUYASABKAUi",
            "sQEKDlBST0NFU1NfQ09ORklHEhoKEkx1YUNvbnRleHRRdWFudGl0eRgBIAEo",
            "BRIXCg9MdWFTY3JpcHRGb2xkZXIYAiABKAkSFAoMTHVhRW50cnlGaWxlGAMg",
            "ASgJEhgKEEx1YUVudHJ5RnVuY3Rpb24YBCABKAkSGgoSTHVhUHJvY2Vzc0Z1",
            "bmN0aW9uGAUgASgJEh4KFkx1YVNvY2tldENsb3NlRnVuY3Rpb24YBiABKAkq",
            "ZQoKTW9kdWxlVHlwZRIQCgxVbmNvbmZpZ3VyZWQQABILCgdDb250cm9sEAES",
            "DAoIRmlyZXdhbGwQAhILCgdHYXRld2F5EAMSCAoERGF0YRAEEgsKB1Byb2Nl",
            "c3MQBRIGCgJEQhAGKjEKClJlc3VsdFR5cGUSCwoHU3VjY2VlZBAAEgkKBUVy",
            "cm9yEAESCwoHV2FybmluZxACKl4KCExvZ0xldmVsEgcKA0FsbBAAEgoKBlZl",
            "cmJvcxABEgkKBURlYnVnEAISCAoESW5mbxADEggKBFdhcm4QBBIHCgNFcnIQ",
            "BRIKCgZBc3NlcnQQBhIJCgVGYXRhbBAHKtMBCglGdW5jdGlvbnMSEQoNUmVn",
            "aXN0ZVNlcnZlchAAEhUKEUdldFdhaXRDb25maWdMaXN0EAESGQoVR2V0Q29u",
            "ZmlnVGVtcGxhdGVMaXN0EAISGwoXU2V0U2VydmVyQ29uZmlnVGVtcGxhdGUQ",
            "AxIXChNTZXRTZXJ2ZXJUb1RlbXBsYXRlEAQSEwoPU2V0U2VydmVyQ29uZmln",
            "EAUSEwoPR2V0U2VydmVyQ29uZmlnEAYSDQoJVXNlckxvZ2luEAcSEgoOUHJv",
            "Y2Vzc01lc3NhZ2UQCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ModuleType), typeof(global::Protocol.ResultType), typeof(global::Protocol.LogLevel), typeof(global::Protocol.Functions), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.DataPackage), global::Protocol.DataPackage.Parser, new[]{ "Function", "PriorityLevel", "SerialNumber", "CheckString", "Sender", "Receiver", "Result", "Content", "Extend" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.GLOBAL_CONFIG), global::Protocol.GLOBAL_CONFIG.Parser, new[]{ "ListenPort", "EnableSSL", "CertFilePath", "KeyFilePath", "CertPasswd", "ConnectTime", "ReceiveTime", "LogPath", "LogLevel", "DebugMode", "MQThreadQuantity", "EPollThreadQuantity", "ProcessThreadQuantity", "PrioritySize", "Type", "ExConfig" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.CONTROL_CONFIG), global::Protocol.CONTROL_CONFIG.Parser, new[]{ "BlockTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.DB_CONFIG), global::Protocol.DB_CONFIG.Parser, new[]{ "ServerAddress", "ServerPort", "User", "Passwd", "Database" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.DATA_CONFIG), global::Protocol.DATA_CONFIG.Parser, new[]{ "DataReceivePort", "DataRecvTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.GATEWAY_CONFIG), global::Protocol.GATEWAY_CONFIG.Parser, new[]{ "ClientCheckTime", "ClientCheckKey", "TimeoutCheckInterval", "TimeoutTime", "ProcessAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.FIREWALL_CONFIG), global::Protocol.FIREWALL_CONFIG.Parser, new[]{ "BlockTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.PROCESS_CONFIG), global::Protocol.PROCESS_CONFIG.Parser, new[]{ "LuaContextQuantity", "LuaScriptFolder", "LuaEntryFile", "LuaEntryFunction", "LuaProcessFunction", "LuaSocketCloseFunction" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///  Type
  /// </summary>
  public enum ModuleType {
    [pbr::OriginalName("Unconfigured")] Unconfigured = 0,
    [pbr::OriginalName("Control")] Control = 1,
    [pbr::OriginalName("Firewall")] Firewall = 2,
    [pbr::OriginalName("Gateway")] Gateway = 3,
    [pbr::OriginalName("Data")] Data = 4,
    [pbr::OriginalName("Process")] Process = 5,
    [pbr::OriginalName("DB")] Db = 6,
  }

  /// <summary>
  ///  Result
  /// </summary>
  public enum ResultType {
    [pbr::OriginalName("Succeed")] Succeed = 0,
    [pbr::OriginalName("Error")] Error = 1,
    [pbr::OriginalName("Warning")] Warning = 2,
  }

  /// <summary>
  ///  LogLevel
  /// </summary>
  public enum LogLevel {
    [pbr::OriginalName("All")] All = 0,
    [pbr::OriginalName("Verbos")] Verbos = 1,
    [pbr::OriginalName("Debug")] Debug = 2,
    [pbr::OriginalName("Info")] Info = 3,
    [pbr::OriginalName("Warn")] Warn = 4,
    [pbr::OriginalName("Err")] Err = 5,
    [pbr::OriginalName("Assert")] Assert = 6,
    [pbr::OriginalName("Fatal")] Fatal = 7,
  }

  public enum Functions {
    /// <summary>
    ///  Flow: ContrulUI -> Control
    /// Response: Content(string) - the uuid for sender.
    /// </summary>
    [pbr::OriginalName("RegisteServer")] RegisteServer = 0,
    /// <summary>
    ///  Flow: ContrulUI -> Control
    /// Response: Content(JSON) - wait config list. 
    /// Format: 
    /// {
    /// "WaitConfigList": [
    /// {
    /// "UUID": "",
    /// "IP": ""
    /// }
    /// ]
    /// }
    /// </summary>
    [pbr::OriginalName("GetWaitConfigList")] GetWaitConfigList = 1,
    /// <summary>
    ///  Flow: ControlUI -> Control
    /// Response: Content(JSON) - Config template  list.
    /// Format: 
    /// {
    /// "ConfigTemplateList": [
    /// {
    /// "ID": "",
    /// "Config": "" //Base64
    /// }
    /// ]
    /// }
    /// </summary>
    [pbr::OriginalName("GetConfigTemplateList")] GetConfigTemplateList = 2,
    /// <summary>
    ///  Flow: ControlUI -> Control
    /// Request: Content - Config template ID
    /// Extend - Target template config
    /// Response: Result
    /// </summary>
    [pbr::OriginalName("SetServerConfigTemplate")] SetServerConfigTemplate = 3,
    /// <summary>
    ///  Flow: ControlUI -> Control
    /// Request: Content(JSON) - config info.
    /// Format:
    /// {
    /// "ServerUUID":"",
    /// "TemplateID":"",
    /// }
    /// Response: Result
    /// </summary>
    [pbr::OriginalName("SetServerToTemplate")] SetServerToTemplate = 4,
    /// <summary>
    ///  Flow: ControlUI -> Control
    /// Request: Content - Target server UUID
    /// Extend - Target server config
    /// Response: Result
    /// </summary>
    [pbr::OriginalName("SetServerConfig")] SetServerConfig = 5,
    /// <summary>
    ///  Sender: All 
    /// Processer: Control
    /// Response: ExtendData(bytes) - config data is not UTF8 string. cannot save in context field.
    /// Note: Get the general server config data. the data type is GLOBAL_CONFIG.
    /// </summary>
    [pbr::OriginalName("GetServerConfig")] GetServerConfig = 6,
    /// <summary>
    ///  Sender: Process 
    ///  Processer: Control
    ///  Response: No
    ///  Note: if the socket uuid is registed, the control will send error message 
    /// </summary>
    [pbr::OriginalName("UserLogin")] UserLogin = 7,
    /// <summary>
    ///  Sender: Procxy
    /// Processer : Process 
    /// Response data: Content - result with JSON string. 
    /// </summary>
    [pbr::OriginalName("ProcessMessage")] ProcessMessage = 8,
  }

  #endregion

  #region Messages
  public sealed partial class DataPackage : pb::IMessage<DataPackage> {
    private static readonly pb::MessageParser<DataPackage> _parser = new pb::MessageParser<DataPackage>(() => new DataPackage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPackage(DataPackage other) : this() {
      function_ = other.function_;
      priorityLevel_ = other.priorityLevel_;
      serialNumber_ = other.serialNumber_;
      checkString_ = other.checkString_;
      sender_ = other.sender_;
      receiver_ = other.receiver_;
      result_ = other.result_;
      content_ = other.content_;
      extend_ = other.extend_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPackage Clone() {
      return new DataPackage(this);
    }

    /// <summary>Field number for the "Function" field.</summary>
    public const int FunctionFieldNumber = 1;
    private global::Protocol.Functions function_ = 0;
    /// <summary>
    ///  功能
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protocol.Functions Function {
      get { return function_; }
      set {
        function_ = value;
      }
    }

    /// <summary>Field number for the "PriorityLevel" field.</summary>
    public const int PriorityLevelFieldNumber = 2;
    private int priorityLevel_;
    /// <summary>
    ///  优先级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PriorityLevel {
      get { return priorityLevel_; }
      set {
        priorityLevel_ = value;
      }
    }

    /// <summary>Field number for the "SerialNumber" field.</summary>
    public const int SerialNumberFieldNumber = 3;
    private long serialNumber_;
    /// <summary>
    ///  流水号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SerialNumber {
      get { return serialNumber_; }
      set {
        serialNumber_ = value;
      }
    }

    /// <summary>Field number for the "CheckString" field.</summary>
    public const int CheckStringFieldNumber = 4;
    private string checkString_ = "";
    /// <summary>
    ///  校验串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CheckString {
      get { return checkString_; }
      set {
        checkString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sender" field.</summary>
    public const int SenderFieldNumber = 5;
    private string sender_ = "";
    /// <summary>
    ///  发送者的唯一标识符
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sender {
      get { return sender_; }
      set {
        sender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Receiver" field.</summary>
    public const int ReceiverFieldNumber = 6;
    private int receiver_;
    /// <summary>
    ///  指定接收者为指定类型的所有成员
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Receiver {
      get { return receiver_; }
      set {
        receiver_ = value;
      }
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 7;
    private global::Protocol.ResultType result_ = 0;
    /// <summary>
    ///  结果代码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protocol.ResultType Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "Content" field.</summary>
    public const int ContentFieldNumber = 8;
    private string content_ = "";
    /// <summary>
    ///  消息内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Extend" field.</summary>
    public const int ExtendFieldNumber = 9;
    private pb::ByteString extend_ = pb::ByteString.Empty;
    /// <summary>
    ///  扩展数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Extend {
      get { return extend_; }
      set {
        extend_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Function != other.Function) return false;
      if (PriorityLevel != other.PriorityLevel) return false;
      if (SerialNumber != other.SerialNumber) return false;
      if (CheckString != other.CheckString) return false;
      if (Sender != other.Sender) return false;
      if (Receiver != other.Receiver) return false;
      if (Result != other.Result) return false;
      if (Content != other.Content) return false;
      if (Extend != other.Extend) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Function != 0) hash ^= Function.GetHashCode();
      if (PriorityLevel != 0) hash ^= PriorityLevel.GetHashCode();
      if (SerialNumber != 0L) hash ^= SerialNumber.GetHashCode();
      if (CheckString.Length != 0) hash ^= CheckString.GetHashCode();
      if (Sender.Length != 0) hash ^= Sender.GetHashCode();
      if (Receiver != 0) hash ^= Receiver.GetHashCode();
      if (Result != 0) hash ^= Result.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (Extend.Length != 0) hash ^= Extend.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Function != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Function);
      }
      if (PriorityLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PriorityLevel);
      }
      if (SerialNumber != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SerialNumber);
      }
      if (CheckString.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CheckString);
      }
      if (Sender.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Sender);
      }
      if (Receiver != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Receiver);
      }
      if (Result != 0) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Result);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Content);
      }
      if (Extend.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(Extend);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Function != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Function);
      }
      if (PriorityLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PriorityLevel);
      }
      if (SerialNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SerialNumber);
      }
      if (CheckString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CheckString);
      }
      if (Sender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sender);
      }
      if (Receiver != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Receiver);
      }
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (Extend.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Extend);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataPackage other) {
      if (other == null) {
        return;
      }
      if (other.Function != 0) {
        Function = other.Function;
      }
      if (other.PriorityLevel != 0) {
        PriorityLevel = other.PriorityLevel;
      }
      if (other.SerialNumber != 0L) {
        SerialNumber = other.SerialNumber;
      }
      if (other.CheckString.Length != 0) {
        CheckString = other.CheckString;
      }
      if (other.Sender.Length != 0) {
        Sender = other.Sender;
      }
      if (other.Receiver != 0) {
        Receiver = other.Receiver;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.Extend.Length != 0) {
        Extend = other.Extend;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            function_ = (global::Protocol.Functions) input.ReadEnum();
            break;
          }
          case 16: {
            PriorityLevel = input.ReadInt32();
            break;
          }
          case 24: {
            SerialNumber = input.ReadInt64();
            break;
          }
          case 34: {
            CheckString = input.ReadString();
            break;
          }
          case 42: {
            Sender = input.ReadString();
            break;
          }
          case 48: {
            Receiver = input.ReadInt32();
            break;
          }
          case 56: {
            result_ = (global::Protocol.ResultType) input.ReadEnum();
            break;
          }
          case 66: {
            Content = input.ReadString();
            break;
          }
          case 74: {
            Extend = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GLOBAL_CONFIG : pb::IMessage<GLOBAL_CONFIG> {
    private static readonly pb::MessageParser<GLOBAL_CONFIG> _parser = new pb::MessageParser<GLOBAL_CONFIG>(() => new GLOBAL_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GLOBAL_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GLOBAL_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GLOBAL_CONFIG(GLOBAL_CONFIG other) : this() {
      listenPort_ = other.listenPort_;
      enableSSL_ = other.enableSSL_;
      certFilePath_ = other.certFilePath_;
      keyFilePath_ = other.keyFilePath_;
      certPasswd_ = other.certPasswd_;
      connectTime_ = other.connectTime_;
      receiveTime_ = other.receiveTime_;
      logPath_ = other.logPath_;
      logLevel_ = other.logLevel_;
      debugMode_ = other.debugMode_;
      mQThreadQuantity_ = other.mQThreadQuantity_;
      ePollThreadQuantity_ = other.ePollThreadQuantity_;
      processThreadQuantity_ = other.processThreadQuantity_;
      prioritySize_ = other.prioritySize_;
      type_ = other.type_;
      exConfig_ = other.exConfig_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GLOBAL_CONFIG Clone() {
      return new GLOBAL_CONFIG(this);
    }

    /// <summary>Field number for the "ListenPort" field.</summary>
    public const int ListenPortFieldNumber = 1;
    private int listenPort_;
    /// <summary>
    ///  Network 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ListenPort {
      get { return listenPort_; }
      set {
        listenPort_ = value;
      }
    }

    /// <summary>Field number for the "EnableSSL" field.</summary>
    public const int EnableSSLFieldNumber = 2;
    private bool enableSSL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EnableSSL {
      get { return enableSSL_; }
      set {
        enableSSL_ = value;
      }
    }

    /// <summary>Field number for the "CertFilePath" field.</summary>
    public const int CertFilePathFieldNumber = 3;
    private string certFilePath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CertFilePath {
      get { return certFilePath_; }
      set {
        certFilePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "KeyFilePath" field.</summary>
    public const int KeyFilePathFieldNumber = 4;
    private string keyFilePath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KeyFilePath {
      get { return keyFilePath_; }
      set {
        keyFilePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CertPasswd" field.</summary>
    public const int CertPasswdFieldNumber = 5;
    private string certPasswd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CertPasswd {
      get { return certPasswd_; }
      set {
        certPasswd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ConnectTime" field.</summary>
    public const int ConnectTimeFieldNumber = 6;
    private int connectTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConnectTime {
      get { return connectTime_; }
      set {
        connectTime_ = value;
      }
    }

    /// <summary>Field number for the "ReceiveTime" field.</summary>
    public const int ReceiveTimeFieldNumber = 7;
    private int receiveTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ReceiveTime {
      get { return receiveTime_; }
      set {
        receiveTime_ = value;
      }
    }

    /// <summary>Field number for the "LogPath" field.</summary>
    public const int LogPathFieldNumber = 8;
    private string logPath_ = "";
    /// <summary>
    ///  Log 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LogPath {
      get { return logPath_; }
      set {
        logPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LogLevel" field.</summary>
    public const int LogLevelFieldNumber = 9;
    private global::Protocol.LogLevel logLevel_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protocol.LogLevel LogLevel {
      get { return logLevel_; }
      set {
        logLevel_ = value;
      }
    }

    /// <summary>Field number for the "DebugMode" field.</summary>
    public const int DebugModeFieldNumber = 10;
    private bool debugMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DebugMode {
      get { return debugMode_; }
      set {
        debugMode_ = value;
      }
    }

    /// <summary>Field number for the "MQThreadQuantity" field.</summary>
    public const int MQThreadQuantityFieldNumber = 11;
    private int mQThreadQuantity_;
    /// <summary>
    ///  Performance
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MQThreadQuantity {
      get { return mQThreadQuantity_; }
      set {
        mQThreadQuantity_ = value;
      }
    }

    /// <summary>Field number for the "EPollThreadQuantity" field.</summary>
    public const int EPollThreadQuantityFieldNumber = 12;
    private int ePollThreadQuantity_;
    /// <summary>
    ///  EPoll event process thread quantity
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EPollThreadQuantity {
      get { return ePollThreadQuantity_; }
      set {
        ePollThreadQuantity_ = value;
      }
    }

    /// <summary>Field number for the "ProcessThreadQuantity" field.</summary>
    public const int ProcessThreadQuantityFieldNumber = 13;
    private int processThreadQuantity_;
    /// <summary>
    ///  work thread for DataPackage process quantity
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ProcessThreadQuantity {
      get { return processThreadQuantity_; }
      set {
        processThreadQuantity_ = value;
      }
    }

    /// <summary>Field number for the "PrioritySize" field.</summary>
    public const int PrioritySizeFieldNumber = 14;
    private int prioritySize_;
    /// <summary>
    ///  Priority Size for the list. the priority level cannot bigger than this value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PrioritySize {
      get { return prioritySize_; }
      set {
        prioritySize_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 15;
    private global::Protocol.ModuleType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protocol.ModuleType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "ExConfig" field.</summary>
    public const int ExConfigFieldNumber = 16;
    private pb::ByteString exConfig_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ExConfig {
      get { return exConfig_; }
      set {
        exConfig_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GLOBAL_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GLOBAL_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ListenPort != other.ListenPort) return false;
      if (EnableSSL != other.EnableSSL) return false;
      if (CertFilePath != other.CertFilePath) return false;
      if (KeyFilePath != other.KeyFilePath) return false;
      if (CertPasswd != other.CertPasswd) return false;
      if (ConnectTime != other.ConnectTime) return false;
      if (ReceiveTime != other.ReceiveTime) return false;
      if (LogPath != other.LogPath) return false;
      if (LogLevel != other.LogLevel) return false;
      if (DebugMode != other.DebugMode) return false;
      if (MQThreadQuantity != other.MQThreadQuantity) return false;
      if (EPollThreadQuantity != other.EPollThreadQuantity) return false;
      if (ProcessThreadQuantity != other.ProcessThreadQuantity) return false;
      if (PrioritySize != other.PrioritySize) return false;
      if (Type != other.Type) return false;
      if (ExConfig != other.ExConfig) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ListenPort != 0) hash ^= ListenPort.GetHashCode();
      if (EnableSSL != false) hash ^= EnableSSL.GetHashCode();
      if (CertFilePath.Length != 0) hash ^= CertFilePath.GetHashCode();
      if (KeyFilePath.Length != 0) hash ^= KeyFilePath.GetHashCode();
      if (CertPasswd.Length != 0) hash ^= CertPasswd.GetHashCode();
      if (ConnectTime != 0) hash ^= ConnectTime.GetHashCode();
      if (ReceiveTime != 0) hash ^= ReceiveTime.GetHashCode();
      if (LogPath.Length != 0) hash ^= LogPath.GetHashCode();
      if (LogLevel != 0) hash ^= LogLevel.GetHashCode();
      if (DebugMode != false) hash ^= DebugMode.GetHashCode();
      if (MQThreadQuantity != 0) hash ^= MQThreadQuantity.GetHashCode();
      if (EPollThreadQuantity != 0) hash ^= EPollThreadQuantity.GetHashCode();
      if (ProcessThreadQuantity != 0) hash ^= ProcessThreadQuantity.GetHashCode();
      if (PrioritySize != 0) hash ^= PrioritySize.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ExConfig.Length != 0) hash ^= ExConfig.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ListenPort != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ListenPort);
      }
      if (EnableSSL != false) {
        output.WriteRawTag(16);
        output.WriteBool(EnableSSL);
      }
      if (CertFilePath.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CertFilePath);
      }
      if (KeyFilePath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(KeyFilePath);
      }
      if (CertPasswd.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CertPasswd);
      }
      if (ConnectTime != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ConnectTime);
      }
      if (ReceiveTime != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ReceiveTime);
      }
      if (LogPath.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LogPath);
      }
      if (LogLevel != 0) {
        output.WriteRawTag(72);
        output.WriteEnum((int) LogLevel);
      }
      if (DebugMode != false) {
        output.WriteRawTag(80);
        output.WriteBool(DebugMode);
      }
      if (MQThreadQuantity != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(MQThreadQuantity);
      }
      if (EPollThreadQuantity != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(EPollThreadQuantity);
      }
      if (ProcessThreadQuantity != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(ProcessThreadQuantity);
      }
      if (PrioritySize != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(PrioritySize);
      }
      if (Type != 0) {
        output.WriteRawTag(120);
        output.WriteEnum((int) Type);
      }
      if (ExConfig.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteBytes(ExConfig);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ListenPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ListenPort);
      }
      if (EnableSSL != false) {
        size += 1 + 1;
      }
      if (CertFilePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CertFilePath);
      }
      if (KeyFilePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyFilePath);
      }
      if (CertPasswd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CertPasswd);
      }
      if (ConnectTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConnectTime);
      }
      if (ReceiveTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceiveTime);
      }
      if (LogPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LogPath);
      }
      if (LogLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LogLevel);
      }
      if (DebugMode != false) {
        size += 1 + 1;
      }
      if (MQThreadQuantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MQThreadQuantity);
      }
      if (EPollThreadQuantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EPollThreadQuantity);
      }
      if (ProcessThreadQuantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProcessThreadQuantity);
      }
      if (PrioritySize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PrioritySize);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (ExConfig.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(ExConfig);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GLOBAL_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.ListenPort != 0) {
        ListenPort = other.ListenPort;
      }
      if (other.EnableSSL != false) {
        EnableSSL = other.EnableSSL;
      }
      if (other.CertFilePath.Length != 0) {
        CertFilePath = other.CertFilePath;
      }
      if (other.KeyFilePath.Length != 0) {
        KeyFilePath = other.KeyFilePath;
      }
      if (other.CertPasswd.Length != 0) {
        CertPasswd = other.CertPasswd;
      }
      if (other.ConnectTime != 0) {
        ConnectTime = other.ConnectTime;
      }
      if (other.ReceiveTime != 0) {
        ReceiveTime = other.ReceiveTime;
      }
      if (other.LogPath.Length != 0) {
        LogPath = other.LogPath;
      }
      if (other.LogLevel != 0) {
        LogLevel = other.LogLevel;
      }
      if (other.DebugMode != false) {
        DebugMode = other.DebugMode;
      }
      if (other.MQThreadQuantity != 0) {
        MQThreadQuantity = other.MQThreadQuantity;
      }
      if (other.EPollThreadQuantity != 0) {
        EPollThreadQuantity = other.EPollThreadQuantity;
      }
      if (other.ProcessThreadQuantity != 0) {
        ProcessThreadQuantity = other.ProcessThreadQuantity;
      }
      if (other.PrioritySize != 0) {
        PrioritySize = other.PrioritySize;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ExConfig.Length != 0) {
        ExConfig = other.ExConfig;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ListenPort = input.ReadInt32();
            break;
          }
          case 16: {
            EnableSSL = input.ReadBool();
            break;
          }
          case 26: {
            CertFilePath = input.ReadString();
            break;
          }
          case 34: {
            KeyFilePath = input.ReadString();
            break;
          }
          case 42: {
            CertPasswd = input.ReadString();
            break;
          }
          case 48: {
            ConnectTime = input.ReadInt32();
            break;
          }
          case 56: {
            ReceiveTime = input.ReadInt32();
            break;
          }
          case 66: {
            LogPath = input.ReadString();
            break;
          }
          case 72: {
            logLevel_ = (global::Protocol.LogLevel) input.ReadEnum();
            break;
          }
          case 80: {
            DebugMode = input.ReadBool();
            break;
          }
          case 88: {
            MQThreadQuantity = input.ReadInt32();
            break;
          }
          case 96: {
            EPollThreadQuantity = input.ReadInt32();
            break;
          }
          case 104: {
            ProcessThreadQuantity = input.ReadInt32();
            break;
          }
          case 112: {
            PrioritySize = input.ReadInt32();
            break;
          }
          case 120: {
            type_ = (global::Protocol.ModuleType) input.ReadEnum();
            break;
          }
          case 130: {
            ExConfig = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CONTROL_CONFIG : pb::IMessage<CONTROL_CONFIG> {
    private static readonly pb::MessageParser<CONTROL_CONFIG> _parser = new pb::MessageParser<CONTROL_CONFIG>(() => new CONTROL_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CONTROL_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CONTROL_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CONTROL_CONFIG(CONTROL_CONFIG other) : this() {
      blockTime_ = other.blockTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CONTROL_CONFIG Clone() {
      return new CONTROL_CONFIG(this);
    }

    /// <summary>Field number for the "BlockTime" field.</summary>
    public const int BlockTimeFieldNumber = 1;
    private int blockTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockTime {
      get { return blockTime_; }
      set {
        blockTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CONTROL_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CONTROL_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockTime != other.BlockTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockTime != 0) hash ^= BlockTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockTime != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BlockTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CONTROL_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.BlockTime != 0) {
        BlockTime = other.BlockTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            BlockTime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DB_CONFIG : pb::IMessage<DB_CONFIG> {
    private static readonly pb::MessageParser<DB_CONFIG> _parser = new pb::MessageParser<DB_CONFIG>(() => new DB_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DB_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DB_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DB_CONFIG(DB_CONFIG other) : this() {
      serverAddress_ = other.serverAddress_;
      serverPort_ = other.serverPort_;
      user_ = other.user_;
      passwd_ = other.passwd_;
      database_ = other.database_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DB_CONFIG Clone() {
      return new DB_CONFIG(this);
    }

    /// <summary>Field number for the "ServerAddress" field.</summary>
    public const int ServerAddressFieldNumber = 1;
    private string serverAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServerAddress {
      get { return serverAddress_; }
      set {
        serverAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ServerPort" field.</summary>
    public const int ServerPortFieldNumber = 2;
    private int serverPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ServerPort {
      get { return serverPort_; }
      set {
        serverPort_ = value;
      }
    }

    /// <summary>Field number for the "User" field.</summary>
    public const int UserFieldNumber = 3;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Passwd" field.</summary>
    public const int PasswdFieldNumber = 4;
    private string passwd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Passwd {
      get { return passwd_; }
      set {
        passwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Database" field.</summary>
    public const int DatabaseFieldNumber = 5;
    private string database_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Database {
      get { return database_; }
      set {
        database_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DB_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DB_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerAddress != other.ServerAddress) return false;
      if (ServerPort != other.ServerPort) return false;
      if (User != other.User) return false;
      if (Passwd != other.Passwd) return false;
      if (Database != other.Database) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerAddress.Length != 0) hash ^= ServerAddress.GetHashCode();
      if (ServerPort != 0) hash ^= ServerPort.GetHashCode();
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Passwd.Length != 0) hash ^= Passwd.GetHashCode();
      if (Database.Length != 0) hash ^= Database.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServerAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerAddress);
      }
      if (ServerPort != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ServerPort);
      }
      if (User.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(User);
      }
      if (Passwd.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Passwd);
      }
      if (Database.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Database);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerAddress);
      }
      if (ServerPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerPort);
      }
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Passwd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Passwd);
      }
      if (Database.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Database);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DB_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.ServerAddress.Length != 0) {
        ServerAddress = other.ServerAddress;
      }
      if (other.ServerPort != 0) {
        ServerPort = other.ServerPort;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Passwd.Length != 0) {
        Passwd = other.Passwd;
      }
      if (other.Database.Length != 0) {
        Database = other.Database;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ServerAddress = input.ReadString();
            break;
          }
          case 16: {
            ServerPort = input.ReadInt32();
            break;
          }
          case 26: {
            User = input.ReadString();
            break;
          }
          case 34: {
            Passwd = input.ReadString();
            break;
          }
          case 42: {
            Database = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DATA_CONFIG : pb::IMessage<DATA_CONFIG> {
    private static readonly pb::MessageParser<DATA_CONFIG> _parser = new pb::MessageParser<DATA_CONFIG>(() => new DATA_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DATA_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DATA_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DATA_CONFIG(DATA_CONFIG other) : this() {
      dataReceivePort_ = other.dataReceivePort_;
      dataRecvTime_ = other.dataRecvTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DATA_CONFIG Clone() {
      return new DATA_CONFIG(this);
    }

    /// <summary>Field number for the "DataReceivePort" field.</summary>
    public const int DataReceivePortFieldNumber = 1;
    private int dataReceivePort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DataReceivePort {
      get { return dataReceivePort_; }
      set {
        dataReceivePort_ = value;
      }
    }

    /// <summary>Field number for the "DataRecvTime" field.</summary>
    public const int DataRecvTimeFieldNumber = 2;
    private int dataRecvTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DataRecvTime {
      get { return dataRecvTime_; }
      set {
        dataRecvTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DATA_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DATA_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DataReceivePort != other.DataReceivePort) return false;
      if (DataRecvTime != other.DataRecvTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DataReceivePort != 0) hash ^= DataReceivePort.GetHashCode();
      if (DataRecvTime != 0) hash ^= DataRecvTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DataReceivePort != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DataReceivePort);
      }
      if (DataRecvTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DataRecvTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DataReceivePort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataReceivePort);
      }
      if (DataRecvTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataRecvTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DATA_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.DataReceivePort != 0) {
        DataReceivePort = other.DataReceivePort;
      }
      if (other.DataRecvTime != 0) {
        DataRecvTime = other.DataRecvTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            DataReceivePort = input.ReadInt32();
            break;
          }
          case 16: {
            DataRecvTime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GATEWAY_CONFIG : pb::IMessage<GATEWAY_CONFIG> {
    private static readonly pb::MessageParser<GATEWAY_CONFIG> _parser = new pb::MessageParser<GATEWAY_CONFIG>(() => new GATEWAY_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GATEWAY_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GATEWAY_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GATEWAY_CONFIG(GATEWAY_CONFIG other) : this() {
      clientCheckTime_ = other.clientCheckTime_;
      clientCheckKey_ = other.clientCheckKey_;
      timeoutCheckInterval_ = other.timeoutCheckInterval_;
      timeoutTime_ = other.timeoutTime_;
      processAddress_ = other.processAddress_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GATEWAY_CONFIG Clone() {
      return new GATEWAY_CONFIG(this);
    }

    /// <summary>Field number for the "ClientCheckTime" field.</summary>
    public const int ClientCheckTimeFieldNumber = 1;
    private int clientCheckTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ClientCheckTime {
      get { return clientCheckTime_; }
      set {
        clientCheckTime_ = value;
      }
    }

    /// <summary>Field number for the "ClientCheckKey" field.</summary>
    public const int ClientCheckKeyFieldNumber = 2;
    private string clientCheckKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientCheckKey {
      get { return clientCheckKey_; }
      set {
        clientCheckKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TimeoutCheckInterval" field.</summary>
    public const int TimeoutCheckIntervalFieldNumber = 3;
    private int timeoutCheckInterval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TimeoutCheckInterval {
      get { return timeoutCheckInterval_; }
      set {
        timeoutCheckInterval_ = value;
      }
    }

    /// <summary>Field number for the "TimeoutTime" field.</summary>
    public const int TimeoutTimeFieldNumber = 4;
    private int timeoutTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TimeoutTime {
      get { return timeoutTime_; }
      set {
        timeoutTime_ = value;
      }
    }

    /// <summary>Field number for the "ProcessAddress" field.</summary>
    public const int ProcessAddressFieldNumber = 5;
    private string processAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProcessAddress {
      get { return processAddress_; }
      set {
        processAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GATEWAY_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GATEWAY_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientCheckTime != other.ClientCheckTime) return false;
      if (ClientCheckKey != other.ClientCheckKey) return false;
      if (TimeoutCheckInterval != other.TimeoutCheckInterval) return false;
      if (TimeoutTime != other.TimeoutTime) return false;
      if (ProcessAddress != other.ProcessAddress) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientCheckTime != 0) hash ^= ClientCheckTime.GetHashCode();
      if (ClientCheckKey.Length != 0) hash ^= ClientCheckKey.GetHashCode();
      if (TimeoutCheckInterval != 0) hash ^= TimeoutCheckInterval.GetHashCode();
      if (TimeoutTime != 0) hash ^= TimeoutTime.GetHashCode();
      if (ProcessAddress.Length != 0) hash ^= ProcessAddress.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientCheckTime != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientCheckTime);
      }
      if (ClientCheckKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientCheckKey);
      }
      if (TimeoutCheckInterval != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TimeoutCheckInterval);
      }
      if (TimeoutTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TimeoutTime);
      }
      if (ProcessAddress.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProcessAddress);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientCheckTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientCheckTime);
      }
      if (ClientCheckKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientCheckKey);
      }
      if (TimeoutCheckInterval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimeoutCheckInterval);
      }
      if (TimeoutTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimeoutTime);
      }
      if (ProcessAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProcessAddress);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GATEWAY_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.ClientCheckTime != 0) {
        ClientCheckTime = other.ClientCheckTime;
      }
      if (other.ClientCheckKey.Length != 0) {
        ClientCheckKey = other.ClientCheckKey;
      }
      if (other.TimeoutCheckInterval != 0) {
        TimeoutCheckInterval = other.TimeoutCheckInterval;
      }
      if (other.TimeoutTime != 0) {
        TimeoutTime = other.TimeoutTime;
      }
      if (other.ProcessAddress.Length != 0) {
        ProcessAddress = other.ProcessAddress;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ClientCheckTime = input.ReadInt32();
            break;
          }
          case 18: {
            ClientCheckKey = input.ReadString();
            break;
          }
          case 24: {
            TimeoutCheckInterval = input.ReadInt32();
            break;
          }
          case 32: {
            TimeoutTime = input.ReadInt32();
            break;
          }
          case 42: {
            ProcessAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FIREWALL_CONFIG : pb::IMessage<FIREWALL_CONFIG> {
    private static readonly pb::MessageParser<FIREWALL_CONFIG> _parser = new pb::MessageParser<FIREWALL_CONFIG>(() => new FIREWALL_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FIREWALL_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FIREWALL_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FIREWALL_CONFIG(FIREWALL_CONFIG other) : this() {
      blockTime_ = other.blockTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FIREWALL_CONFIG Clone() {
      return new FIREWALL_CONFIG(this);
    }

    /// <summary>Field number for the "BlockTime" field.</summary>
    public const int BlockTimeFieldNumber = 1;
    private int blockTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BlockTime {
      get { return blockTime_; }
      set {
        blockTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FIREWALL_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FIREWALL_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockTime != other.BlockTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockTime != 0) hash ^= BlockTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockTime != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BlockTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BlockTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FIREWALL_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.BlockTime != 0) {
        BlockTime = other.BlockTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            BlockTime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PROCESS_CONFIG : pb::IMessage<PROCESS_CONFIG> {
    private static readonly pb::MessageParser<PROCESS_CONFIG> _parser = new pb::MessageParser<PROCESS_CONFIG>(() => new PROCESS_CONFIG());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PROCESS_CONFIG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PROCESS_CONFIG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PROCESS_CONFIG(PROCESS_CONFIG other) : this() {
      luaContextQuantity_ = other.luaContextQuantity_;
      luaScriptFolder_ = other.luaScriptFolder_;
      luaEntryFile_ = other.luaEntryFile_;
      luaEntryFunction_ = other.luaEntryFunction_;
      luaProcessFunction_ = other.luaProcessFunction_;
      luaSocketCloseFunction_ = other.luaSocketCloseFunction_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PROCESS_CONFIG Clone() {
      return new PROCESS_CONFIG(this);
    }

    /// <summary>Field number for the "LuaContextQuantity" field.</summary>
    public const int LuaContextQuantityFieldNumber = 1;
    private int luaContextQuantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LuaContextQuantity {
      get { return luaContextQuantity_; }
      set {
        luaContextQuantity_ = value;
      }
    }

    /// <summary>Field number for the "LuaScriptFolder" field.</summary>
    public const int LuaScriptFolderFieldNumber = 2;
    private string luaScriptFolder_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaScriptFolder {
      get { return luaScriptFolder_; }
      set {
        luaScriptFolder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaEntryFile" field.</summary>
    public const int LuaEntryFileFieldNumber = 3;
    private string luaEntryFile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaEntryFile {
      get { return luaEntryFile_; }
      set {
        luaEntryFile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaEntryFunction" field.</summary>
    public const int LuaEntryFunctionFieldNumber = 4;
    private string luaEntryFunction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaEntryFunction {
      get { return luaEntryFunction_; }
      set {
        luaEntryFunction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaProcessFunction" field.</summary>
    public const int LuaProcessFunctionFieldNumber = 5;
    private string luaProcessFunction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaProcessFunction {
      get { return luaProcessFunction_; }
      set {
        luaProcessFunction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaSocketCloseFunction" field.</summary>
    public const int LuaSocketCloseFunctionFieldNumber = 6;
    private string luaSocketCloseFunction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaSocketCloseFunction {
      get { return luaSocketCloseFunction_; }
      set {
        luaSocketCloseFunction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PROCESS_CONFIG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PROCESS_CONFIG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LuaContextQuantity != other.LuaContextQuantity) return false;
      if (LuaScriptFolder != other.LuaScriptFolder) return false;
      if (LuaEntryFile != other.LuaEntryFile) return false;
      if (LuaEntryFunction != other.LuaEntryFunction) return false;
      if (LuaProcessFunction != other.LuaProcessFunction) return false;
      if (LuaSocketCloseFunction != other.LuaSocketCloseFunction) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LuaContextQuantity != 0) hash ^= LuaContextQuantity.GetHashCode();
      if (LuaScriptFolder.Length != 0) hash ^= LuaScriptFolder.GetHashCode();
      if (LuaEntryFile.Length != 0) hash ^= LuaEntryFile.GetHashCode();
      if (LuaEntryFunction.Length != 0) hash ^= LuaEntryFunction.GetHashCode();
      if (LuaProcessFunction.Length != 0) hash ^= LuaProcessFunction.GetHashCode();
      if (LuaSocketCloseFunction.Length != 0) hash ^= LuaSocketCloseFunction.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LuaContextQuantity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LuaContextQuantity);
      }
      if (LuaScriptFolder.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LuaScriptFolder);
      }
      if (LuaEntryFile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LuaEntryFile);
      }
      if (LuaEntryFunction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LuaEntryFunction);
      }
      if (LuaProcessFunction.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LuaProcessFunction);
      }
      if (LuaSocketCloseFunction.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LuaSocketCloseFunction);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LuaContextQuantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LuaContextQuantity);
      }
      if (LuaScriptFolder.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaScriptFolder);
      }
      if (LuaEntryFile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaEntryFile);
      }
      if (LuaEntryFunction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaEntryFunction);
      }
      if (LuaProcessFunction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaProcessFunction);
      }
      if (LuaSocketCloseFunction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaSocketCloseFunction);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PROCESS_CONFIG other) {
      if (other == null) {
        return;
      }
      if (other.LuaContextQuantity != 0) {
        LuaContextQuantity = other.LuaContextQuantity;
      }
      if (other.LuaScriptFolder.Length != 0) {
        LuaScriptFolder = other.LuaScriptFolder;
      }
      if (other.LuaEntryFile.Length != 0) {
        LuaEntryFile = other.LuaEntryFile;
      }
      if (other.LuaEntryFunction.Length != 0) {
        LuaEntryFunction = other.LuaEntryFunction;
      }
      if (other.LuaProcessFunction.Length != 0) {
        LuaProcessFunction = other.LuaProcessFunction;
      }
      if (other.LuaSocketCloseFunction.Length != 0) {
        LuaSocketCloseFunction = other.LuaSocketCloseFunction;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            LuaContextQuantity = input.ReadInt32();
            break;
          }
          case 18: {
            LuaScriptFolder = input.ReadString();
            break;
          }
          case 26: {
            LuaEntryFile = input.ReadString();
            break;
          }
          case 34: {
            LuaEntryFunction = input.ReadString();
            break;
          }
          case 42: {
            LuaProcessFunction = input.ReadString();
            break;
          }
          case 50: {
            LuaSocketCloseFunction = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
