// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#ifndef PROTOBUF_INCLUDED_core_2eproto
#define PROTOBUF_INCLUDED_core_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_core_2eproto 

namespace protobuf_core_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_core_2eproto
namespace Core {
class DataPackage;
class DataPackageDefaultTypeInternal;
extern DataPackageDefaultTypeInternal _DataPackage_default_instance_;
class GLOBAL_CONFIG;
class GLOBAL_CONFIGDefaultTypeInternal;
extern GLOBAL_CONFIGDefaultTypeInternal _GLOBAL_CONFIG_default_instance_;
class RuntimeDataPackage;
class RuntimeDataPackageDefaultTypeInternal;
extern RuntimeDataPackageDefaultTypeInternal _RuntimeDataPackage_default_instance_;
}  // namespace Core
namespace google {
namespace protobuf {
template<> ::Core::DataPackage* Arena::CreateMaybeMessage<::Core::DataPackage>(Arena*);
template<> ::Core::GLOBAL_CONFIG* Arena::CreateMaybeMessage<::Core::GLOBAL_CONFIG>(Arena*);
template<> ::Core::RuntimeDataPackage* Arena::CreateMaybeMessage<::Core::RuntimeDataPackage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Core {

enum DataPackage_PackageType {
  DataPackage_PackageType_RequestPackage = 0,
  DataPackage_PackageType_EventPackage = 1,
  DataPackage_PackageType_DataPackage_PackageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DataPackage_PackageType_DataPackage_PackageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DataPackage_PackageType_IsValid(int value);
const DataPackage_PackageType DataPackage_PackageType_PackageType_MIN = DataPackage_PackageType_RequestPackage;
const DataPackage_PackageType DataPackage_PackageType_PackageType_MAX = DataPackage_PackageType_EventPackage;
const int DataPackage_PackageType_PackageType_ARRAYSIZE = DataPackage_PackageType_PackageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataPackage_PackageType_descriptor();
inline const ::std::string& DataPackage_PackageType_Name(DataPackage_PackageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataPackage_PackageType_descriptor(), value);
}
inline bool DataPackage_PackageType_Parse(
    const ::std::string& name, DataPackage_PackageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataPackage_PackageType>(
    DataPackage_PackageType_descriptor(), name, value);
}
enum DataPackage_StatusType {
  DataPackage_StatusType_Request = 0,
  DataPackage_StatusType_Response = 1,
  DataPackage_StatusType_DataPackage_StatusType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DataPackage_StatusType_DataPackage_StatusType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DataPackage_StatusType_IsValid(int value);
const DataPackage_StatusType DataPackage_StatusType_StatusType_MIN = DataPackage_StatusType_Request;
const DataPackage_StatusType DataPackage_StatusType_StatusType_MAX = DataPackage_StatusType_Response;
const int DataPackage_StatusType_StatusType_ARRAYSIZE = DataPackage_StatusType_StatusType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataPackage_StatusType_descriptor();
inline const ::std::string& DataPackage_StatusType_Name(DataPackage_StatusType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataPackage_StatusType_descriptor(), value);
}
inline bool DataPackage_StatusType_Parse(
    const ::std::string& name, DataPackage_StatusType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataPackage_StatusType>(
    DataPackage_StatusType_descriptor(), name, value);
}
enum ResultType {
  Succeed = 0,
  Error = 1,
  Warning = 2,
  Retry = 3,
  Invalid = 4,
  ResultType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ResultType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ResultType_IsValid(int value);
const ResultType ResultType_MIN = Succeed;
const ResultType ResultType_MAX = Invalid;
const int ResultType_ARRAYSIZE = ResultType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ResultType_descriptor();
inline const ::std::string& ResultType_Name(ResultType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ResultType_descriptor(), value);
}
inline bool ResultType_Parse(
    const ::std::string& name, ResultType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResultType>(
    ResultType_descriptor(), name, value);
}
enum LogLevel {
  All = 0,
  Verbos = 1,
  Debug = 2,
  Info = 3,
  Warn = 4,
  Err = 5,
  Assert = 6,
  Fatal = 7,
  LogLevel_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogLevel_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogLevel_IsValid(int value);
const LogLevel LogLevel_MIN = All;
const LogLevel LogLevel_MAX = Fatal;
const int LogLevel_ARRAYSIZE = LogLevel_MAX + 1;

const ::google::protobuf::EnumDescriptor* LogLevel_descriptor();
inline const ::std::string& LogLevel_Name(LogLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogLevel_descriptor(), value);
}
inline bool LogLevel_Parse(
    const ::std::string& name, LogLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogLevel>(
    LogLevel_descriptor(), name, value);
}
enum DATA_ITEM {
  ServerConfiguation = 0,
  ModuleConfiguation = 1,
  Logger = 2,
  RuntimeData = 3,
  ReferenceTemplateInfo = 4,
  DATA_ITEM_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DATA_ITEM_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DATA_ITEM_IsValid(int value);
const DATA_ITEM DATA_ITEM_MIN = ServerConfiguation;
const DATA_ITEM DATA_ITEM_MAX = ReferenceTemplateInfo;
const int DATA_ITEM_ARRAYSIZE = DATA_ITEM_MAX + 1;

const ::google::protobuf::EnumDescriptor* DATA_ITEM_descriptor();
inline const ::std::string& DATA_ITEM_Name(DATA_ITEM value) {
  return ::google::protobuf::internal::NameOfEnum(
    DATA_ITEM_descriptor(), value);
}
inline bool DATA_ITEM_Parse(
    const ::std::string& name, DATA_ITEM* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DATA_ITEM>(
    DATA_ITEM_descriptor(), name, value);
}
enum EVENT_TYPE {
  ProgramStart = 0,
  ProgramStop = 1,
  ProgramRestart = 2,
  SocketClose = 3,
  SendPackage = 4,
  MonitorSendStatus = 5,
  EnableTimeoutCheck = 6,
  EnableClientCheck = 7,
  ReloadLuaContext = 8,
  RegisteConnection = 9,
  EVENT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EVENT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EVENT_TYPE_IsValid(int value);
const EVENT_TYPE EVENT_TYPE_MIN = ProgramStart;
const EVENT_TYPE EVENT_TYPE_MAX = RegisteConnection;
const int EVENT_TYPE_ARRAYSIZE = EVENT_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* EVENT_TYPE_descriptor();
inline const ::std::string& EVENT_TYPE_Name(EVENT_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    EVENT_TYPE_descriptor(), value);
}
inline bool EVENT_TYPE_Parse(
    const ::std::string& name, EVENT_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EVENT_TYPE>(
    EVENT_TYPE_descriptor(), name, value);
}
enum PRIORITY_LEVEL {
  HEIGHT_LEVEL = 0,
  NORMAL_LEVEL = 1,
  LOW_LEVEL = 2,
  PRIORITY_LEVEL_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PRIORITY_LEVEL_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PRIORITY_LEVEL_IsValid(int value);
const PRIORITY_LEVEL PRIORITY_LEVEL_MIN = HEIGHT_LEVEL;
const PRIORITY_LEVEL PRIORITY_LEVEL_MAX = LOW_LEVEL;
const int PRIORITY_LEVEL_ARRAYSIZE = PRIORITY_LEVEL_MAX + 1;

const ::google::protobuf::EnumDescriptor* PRIORITY_LEVEL_descriptor();
inline const ::std::string& PRIORITY_LEVEL_Name(PRIORITY_LEVEL value) {
  return ::google::protobuf::internal::NameOfEnum(
    PRIORITY_LEVEL_descriptor(), value);
}
inline bool PRIORITY_LEVEL_Parse(
    const ::std::string& name, PRIORITY_LEVEL* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PRIORITY_LEVEL>(
    PRIORITY_LEVEL_descriptor(), name, value);
}
enum ControlEvent {
  InvalidEvent = 0,
  Restart = 1,
  Stop = 2,
  ControlEvent_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ControlEvent_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ControlEvent_IsValid(int value);
const ControlEvent ControlEvent_MIN = InvalidEvent;
const ControlEvent ControlEvent_MAX = Stop;
const int ControlEvent_ARRAYSIZE = ControlEvent_MAX + 1;

const ::google::protobuf::EnumDescriptor* ControlEvent_descriptor();
inline const ::std::string& ControlEvent_Name(ControlEvent value) {
  return ::google::protobuf::internal::NameOfEnum(
    ControlEvent_descriptor(), value);
}
inline bool ControlEvent_Parse(
    const ::std::string& name, ControlEvent* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ControlEvent>(
    ControlEvent_descriptor(), name, value);
}
// ===================================================================

class DataPackage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Core.DataPackage) */ {
 public:
  DataPackage();
  virtual ~DataPackage();

  DataPackage(const DataPackage& from);

  inline DataPackage& operator=(const DataPackage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DataPackage(DataPackage&& from) noexcept
    : DataPackage() {
    *this = ::std::move(from);
  }

  inline DataPackage& operator=(DataPackage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DataPackage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataPackage* internal_default_instance() {
    return reinterpret_cast<const DataPackage*>(
               &_DataPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DataPackage* other);
  friend void swap(DataPackage& a, DataPackage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DataPackage* New() const final {
    return CreateMaybeMessage<DataPackage>(NULL);
  }

  DataPackage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DataPackage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DataPackage& from);
  void MergeFrom(const DataPackage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataPackage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DataPackage_PackageType PackageType;
  static const PackageType RequestPackage =
    DataPackage_PackageType_RequestPackage;
  static const PackageType EventPackage =
    DataPackage_PackageType_EventPackage;
  static inline bool PackageType_IsValid(int value) {
    return DataPackage_PackageType_IsValid(value);
  }
  static const PackageType PackageType_MIN =
    DataPackage_PackageType_PackageType_MIN;
  static const PackageType PackageType_MAX =
    DataPackage_PackageType_PackageType_MAX;
  static const int PackageType_ARRAYSIZE =
    DataPackage_PackageType_PackageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PackageType_descriptor() {
    return DataPackage_PackageType_descriptor();
  }
  static inline const ::std::string& PackageType_Name(PackageType value) {
    return DataPackage_PackageType_Name(value);
  }
  static inline bool PackageType_Parse(const ::std::string& name,
      PackageType* value) {
    return DataPackage_PackageType_Parse(name, value);
  }

  typedef DataPackage_StatusType StatusType;
  static const StatusType Request =
    DataPackage_StatusType_Request;
  static const StatusType Response =
    DataPackage_StatusType_Response;
  static inline bool StatusType_IsValid(int value) {
    return DataPackage_StatusType_IsValid(value);
  }
  static const StatusType StatusType_MIN =
    DataPackage_StatusType_StatusType_MIN;
  static const StatusType StatusType_MAX =
    DataPackage_StatusType_StatusType_MAX;
  static const int StatusType_ARRAYSIZE =
    DataPackage_StatusType_StatusType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StatusType_descriptor() {
    return DataPackage_StatusType_descriptor();
  }
  static inline const ::std::string& StatusType_Name(StatusType value) {
    return DataPackage_StatusType_Name(value);
  }
  static inline bool StatusType_Parse(const ::std::string& name,
      StatusType* value) {
    return DataPackage_StatusType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // bytes Hash = 6;
  void clear_hash();
  static const int kHashFieldNumber = 6;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const void* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // bytes Content = 9;
  void clear_content();
  static const int kContentFieldNumber = 9;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // bytes Extend = 10;
  void clear_extend();
  static const int kExtendFieldNumber = 10;
  const ::std::string& extend() const;
  void set_extend(const ::std::string& value);
  #if LANG_CXX11
  void set_extend(::std::string&& value);
  #endif
  void set_extend(const char* value);
  void set_extend(const void* value, size_t size);
  ::std::string* mutable_extend();
  ::std::string* release_extend();
  void set_allocated_extend(::std::string* extend);

  // .Core.DataPackage.PackageType Type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Core::DataPackage_PackageType type() const;
  void set_type(::Core::DataPackage_PackageType value);

  // .Core.DataPackage.StatusType Status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::Core::DataPackage_StatusType status() const;
  void set_status(::Core::DataPackage_StatusType value);

  // int32 Function = 3;
  void clear_function();
  static const int kFunctionFieldNumber = 3;
  ::google::protobuf::int32 function() const;
  void set_function(::google::protobuf::int32 value);

  // int32 Priority = 4;
  void clear_priority();
  static const int kPriorityFieldNumber = 4;
  ::google::protobuf::int32 priority() const;
  void set_priority(::google::protobuf::int32 value);

  // fixed64 ID = 5;
  void clear_id();
  static const int kIDFieldNumber = 5;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // fixed64 Sender = 7;
  void clear_sender();
  static const int kSenderFieldNumber = 7;
  ::google::protobuf::uint64 sender() const;
  void set_sender(::google::protobuf::uint64 value);

  // .Core.ResultType Result = 8;
  void clear_result();
  static const int kResultFieldNumber = 8;
  ::Core::ResultType result() const;
  void set_result(::Core::ResultType value);

  // @@protoc_insertion_point(class_scope:Core.DataPackage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::internal::ArenaStringPtr extend_;
  int type_;
  int status_;
  ::google::protobuf::int32 function_;
  ::google::protobuf::int32 priority_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 sender_;
  int result_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GLOBAL_CONFIG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Core.GLOBAL_CONFIG) */ {
 public:
  GLOBAL_CONFIG();
  virtual ~GLOBAL_CONFIG();

  GLOBAL_CONFIG(const GLOBAL_CONFIG& from);

  inline GLOBAL_CONFIG& operator=(const GLOBAL_CONFIG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GLOBAL_CONFIG(GLOBAL_CONFIG&& from) noexcept
    : GLOBAL_CONFIG() {
    *this = ::std::move(from);
  }

  inline GLOBAL_CONFIG& operator=(GLOBAL_CONFIG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GLOBAL_CONFIG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GLOBAL_CONFIG* internal_default_instance() {
    return reinterpret_cast<const GLOBAL_CONFIG*>(
               &_GLOBAL_CONFIG_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GLOBAL_CONFIG* other);
  friend void swap(GLOBAL_CONFIG& a, GLOBAL_CONFIG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GLOBAL_CONFIG* New() const final {
    return CreateMaybeMessage<GLOBAL_CONFIG>(NULL);
  }

  GLOBAL_CONFIG* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GLOBAL_CONFIG>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GLOBAL_CONFIG& from);
  void MergeFrom(const GLOBAL_CONFIG& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GLOBAL_CONFIG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ListenAddress = 1;
  void clear_listenaddress();
  static const int kListenAddressFieldNumber = 1;
  const ::std::string& listenaddress() const;
  void set_listenaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_listenaddress(::std::string&& value);
  #endif
  void set_listenaddress(const char* value);
  void set_listenaddress(const char* value, size_t size);
  ::std::string* mutable_listenaddress();
  ::std::string* release_listenaddress();
  void set_allocated_listenaddress(::std::string* listenaddress);

  // string LogPath = 3;
  void clear_logpath();
  static const int kLogPathFieldNumber = 3;
  const ::std::string& logpath() const;
  void set_logpath(const ::std::string& value);
  #if LANG_CXX11
  void set_logpath(::std::string&& value);
  #endif
  void set_logpath(const char* value);
  void set_logpath(const char* value, size_t size);
  ::std::string* mutable_logpath();
  ::std::string* release_logpath();
  void set_allocated_logpath(::std::string* logpath);

  // string ModuleName = 12;
  void clear_modulename();
  static const int kModuleNameFieldNumber = 12;
  const ::std::string& modulename() const;
  void set_modulename(const ::std::string& value);
  #if LANG_CXX11
  void set_modulename(::std::string&& value);
  #endif
  void set_modulename(const char* value);
  void set_modulename(const char* value, size_t size);
  ::std::string* mutable_modulename();
  ::std::string* release_modulename();
  void set_allocated_modulename(::std::string* modulename);

  // string ModulePath = 13;
  void clear_modulepath();
  static const int kModulePathFieldNumber = 13;
  const ::std::string& modulepath() const;
  void set_modulepath(const ::std::string& value);
  #if LANG_CXX11
  void set_modulepath(::std::string&& value);
  #endif
  void set_modulepath(const char* value);
  void set_modulepath(const char* value, size_t size);
  ::std::string* mutable_modulepath();
  ::std::string* release_modulepath();
  void set_allocated_modulepath(::std::string* modulepath);

  // bytes ModuleConfig = 14;
  void clear_moduleconfig();
  static const int kModuleConfigFieldNumber = 14;
  const ::std::string& moduleconfig() const;
  void set_moduleconfig(const ::std::string& value);
  #if LANG_CXX11
  void set_moduleconfig(::std::string&& value);
  #endif
  void set_moduleconfig(const char* value);
  void set_moduleconfig(const void* value, size_t size);
  ::std::string* mutable_moduleconfig();
  ::std::string* release_moduleconfig();
  void set_allocated_moduleconfig(::std::string* moduleconfig);

  // string ModuleReference = 15;
  void clear_modulereference();
  static const int kModuleReferenceFieldNumber = 15;
  const ::std::string& modulereference() const;
  void set_modulereference(const ::std::string& value);
  #if LANG_CXX11
  void set_modulereference(::std::string&& value);
  #endif
  void set_modulereference(const char* value);
  void set_modulereference(const char* value, size_t size);
  ::std::string* mutable_modulereference();
  ::std::string* release_modulereference();
  void set_allocated_modulereference(::std::string* modulereference);

  // string ModuleFunctoins = 16;
  void clear_modulefunctoins();
  static const int kModuleFunctoinsFieldNumber = 16;
  const ::std::string& modulefunctoins() const;
  void set_modulefunctoins(const ::std::string& value);
  #if LANG_CXX11
  void set_modulefunctoins(::std::string&& value);
  #endif
  void set_modulefunctoins(const char* value);
  void set_modulefunctoins(const char* value, size_t size);
  ::std::string* mutable_modulefunctoins();
  ::std::string* release_modulefunctoins();
  void set_allocated_modulefunctoins(::std::string* modulefunctoins);

  // string CertFilePath = 18;
  void clear_certfilepath();
  static const int kCertFilePathFieldNumber = 18;
  const ::std::string& certfilepath() const;
  void set_certfilepath(const ::std::string& value);
  #if LANG_CXX11
  void set_certfilepath(::std::string&& value);
  #endif
  void set_certfilepath(const char* value);
  void set_certfilepath(const char* value, size_t size);
  ::std::string* mutable_certfilepath();
  ::std::string* release_certfilepath();
  void set_allocated_certfilepath(::std::string* certfilepath);

  // string KeyFilePath = 19;
  void clear_keyfilepath();
  static const int kKeyFilePathFieldNumber = 19;
  const ::std::string& keyfilepath() const;
  void set_keyfilepath(const ::std::string& value);
  #if LANG_CXX11
  void set_keyfilepath(::std::string&& value);
  #endif
  void set_keyfilepath(const char* value);
  void set_keyfilepath(const char* value, size_t size);
  ::std::string* mutable_keyfilepath();
  ::std::string* release_keyfilepath();
  void set_allocated_keyfilepath(::std::string* keyfilepath);

  // string CertPasswd = 20;
  void clear_certpasswd();
  static const int kCertPasswdFieldNumber = 20;
  const ::std::string& certpasswd() const;
  void set_certpasswd(const ::std::string& value);
  #if LANG_CXX11
  void set_certpasswd(::std::string&& value);
  #endif
  void set_certpasswd(const char* value);
  void set_certpasswd(const char* value, size_t size);
  ::std::string* mutable_certpasswd();
  ::std::string* release_certpasswd();
  void set_allocated_certpasswd(::std::string* certpasswd);

  // int32 ListenPort = 2;
  void clear_listenport();
  static const int kListenPortFieldNumber = 2;
  ::google::protobuf::int32 listenport() const;
  void set_listenport(::google::protobuf::int32 value);

  // .Core.LogLevel LogLevel = 4;
  void clear_loglevel();
  static const int kLogLevelFieldNumber = 4;
  ::Core::LogLevel loglevel() const;
  void set_loglevel(::Core::LogLevel value);

  // int32 LogOperation = 5;
  void clear_logoperation();
  static const int kLogOperationFieldNumber = 5;
  ::google::protobuf::int32 logoperation() const;
  void set_logoperation(::google::protobuf::int32 value);

  // int32 MQThreadQuantity = 6;
  void clear_mqthreadquantity();
  static const int kMQThreadQuantityFieldNumber = 6;
  ::google::protobuf::int32 mqthreadquantity() const;
  void set_mqthreadquantity(::google::protobuf::int32 value);

  // int32 EPollThreadQuantity = 7;
  void clear_epollthreadquantity();
  static const int kEPollThreadQuantityFieldNumber = 7;
  ::google::protobuf::int32 epollthreadquantity() const;
  void set_epollthreadquantity(::google::protobuf::int32 value);

  // int32 ProcessThreadQuantity = 8;
  void clear_processthreadquantity();
  static const int kProcessThreadQuantityFieldNumber = 8;
  ::google::protobuf::int32 processthreadquantity() const;
  void set_processthreadquantity(::google::protobuf::int32 value);

  // int32 PrioritySize = 9;
  void clear_prioritysize();
  static const int kPrioritySizeFieldNumber = 9;
  ::google::protobuf::int32 prioritysize() const;
  void set_prioritysize(::google::protobuf::int32 value);

  // int32 ConnectTime = 10;
  void clear_connecttime();
  static const int kConnectTimeFieldNumber = 10;
  ::google::protobuf::int32 connecttime() const;
  void set_connecttime(::google::protobuf::int32 value);

  // int32 ReceiveTime = 11;
  void clear_receivetime();
  static const int kReceiveTimeFieldNumber = 11;
  ::google::protobuf::int32 receivetime() const;
  void set_receivetime(::google::protobuf::int32 value);

  // bool EnableSSL = 17;
  void clear_enablessl();
  static const int kEnableSSLFieldNumber = 17;
  bool enablessl() const;
  void set_enablessl(bool value);

  // @@protoc_insertion_point(class_scope:Core.GLOBAL_CONFIG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr listenaddress_;
  ::google::protobuf::internal::ArenaStringPtr logpath_;
  ::google::protobuf::internal::ArenaStringPtr modulename_;
  ::google::protobuf::internal::ArenaStringPtr modulepath_;
  ::google::protobuf::internal::ArenaStringPtr moduleconfig_;
  ::google::protobuf::internal::ArenaStringPtr modulereference_;
  ::google::protobuf::internal::ArenaStringPtr modulefunctoins_;
  ::google::protobuf::internal::ArenaStringPtr certfilepath_;
  ::google::protobuf::internal::ArenaStringPtr keyfilepath_;
  ::google::protobuf::internal::ArenaStringPtr certpasswd_;
  ::google::protobuf::int32 listenport_;
  int loglevel_;
  ::google::protobuf::int32 logoperation_;
  ::google::protobuf::int32 mqthreadquantity_;
  ::google::protobuf::int32 epollthreadquantity_;
  ::google::protobuf::int32 processthreadquantity_;
  ::google::protobuf::int32 prioritysize_;
  ::google::protobuf::int32 connecttime_;
  ::google::protobuf::int32 receivetime_;
  bool enablessl_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RuntimeDataPackage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Core.RuntimeDataPackage) */ {
 public:
  RuntimeDataPackage();
  virtual ~RuntimeDataPackage();

  RuntimeDataPackage(const RuntimeDataPackage& from);

  inline RuntimeDataPackage& operator=(const RuntimeDataPackage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RuntimeDataPackage(RuntimeDataPackage&& from) noexcept
    : RuntimeDataPackage() {
    *this = ::std::move(from);
  }

  inline RuntimeDataPackage& operator=(RuntimeDataPackage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RuntimeDataPackage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RuntimeDataPackage* internal_default_instance() {
    return reinterpret_cast<const RuntimeDataPackage*>(
               &_RuntimeDataPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RuntimeDataPackage* other);
  friend void swap(RuntimeDataPackage& a, RuntimeDataPackage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RuntimeDataPackage* New() const final {
    return CreateMaybeMessage<RuntimeDataPackage>(NULL);
  }

  RuntimeDataPackage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RuntimeDataPackage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RuntimeDataPackage& from);
  void MergeFrom(const RuntimeDataPackage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RuntimeDataPackage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ManagerAddress = 1;
  void clear_manageraddress();
  static const int kManagerAddressFieldNumber = 1;
  const ::std::string& manageraddress() const;
  void set_manageraddress(const ::std::string& value);
  #if LANG_CXX11
  void set_manageraddress(::std::string&& value);
  #endif
  void set_manageraddress(const char* value);
  void set_manageraddress(const char* value, size_t size);
  ::std::string* mutable_manageraddress();
  ::std::string* release_manageraddress();
  void set_allocated_manageraddress(::std::string* manageraddress);

  // .Core.GLOBAL_CONFIG TemplateConfig = 5;
  bool has_templateconfig() const;
  void clear_templateconfig();
  static const int kTemplateConfigFieldNumber = 5;
  private:
  const ::Core::GLOBAL_CONFIG& _internal_templateconfig() const;
  public:
  const ::Core::GLOBAL_CONFIG& templateconfig() const;
  ::Core::GLOBAL_CONFIG* release_templateconfig();
  ::Core::GLOBAL_CONFIG* mutable_templateconfig();
  void set_allocated_templateconfig(::Core::GLOBAL_CONFIG* templateconfig);

  // int32 ManagerPort = 2;
  void clear_managerport();
  static const int kManagerPortFieldNumber = 2;
  ::google::protobuf::int32 managerport() const;
  void set_managerport(::google::protobuf::int32 value);

  // int32 TemplateID = 3;
  void clear_templateid();
  static const int kTemplateIDFieldNumber = 3;
  ::google::protobuf::int32 templateid() const;
  void set_templateid(::google::protobuf::int32 value);

  // fixed64 NodeUUID = 4;
  void clear_nodeuuid();
  static const int kNodeUUIDFieldNumber = 4;
  ::google::protobuf::uint64 nodeuuid() const;
  void set_nodeuuid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Core.RuntimeDataPackage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr manageraddress_;
  ::Core::GLOBAL_CONFIG* templateconfig_;
  ::google::protobuf::int32 managerport_;
  ::google::protobuf::int32 templateid_;
  ::google::protobuf::uint64 nodeuuid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataPackage

// .Core.DataPackage.PackageType Type = 1;
inline void DataPackage::clear_type() {
  type_ = 0;
}
inline ::Core::DataPackage_PackageType DataPackage::type() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Type)
  return static_cast< ::Core::DataPackage_PackageType >(type_);
}
inline void DataPackage::set_type(::Core::DataPackage_PackageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Type)
}

// .Core.DataPackage.StatusType Status = 2;
inline void DataPackage::clear_status() {
  status_ = 0;
}
inline ::Core::DataPackage_StatusType DataPackage::status() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Status)
  return static_cast< ::Core::DataPackage_StatusType >(status_);
}
inline void DataPackage::set_status(::Core::DataPackage_StatusType value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Status)
}

// int32 Function = 3;
inline void DataPackage::clear_function() {
  function_ = 0;
}
inline ::google::protobuf::int32 DataPackage::function() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Function)
  return function_;
}
inline void DataPackage::set_function(::google::protobuf::int32 value) {
  
  function_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Function)
}

// int32 Priority = 4;
inline void DataPackage::clear_priority() {
  priority_ = 0;
}
inline ::google::protobuf::int32 DataPackage::priority() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Priority)
  return priority_;
}
inline void DataPackage::set_priority(::google::protobuf::int32 value) {
  
  priority_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Priority)
}

// fixed64 ID = 5;
inline void DataPackage::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DataPackage::id() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.ID)
  return id_;
}
inline void DataPackage::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.ID)
}

// bytes Hash = 6;
inline void DataPackage::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DataPackage::hash() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Hash)
  return hash_.GetNoArena();
}
inline void DataPackage::set_hash(const ::std::string& value) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.DataPackage.Hash)
}
#if LANG_CXX11
inline void DataPackage::set_hash(::std::string&& value) {
  
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.DataPackage.Hash)
}
#endif
inline void DataPackage::set_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.DataPackage.Hash)
}
inline void DataPackage::set_hash(const void* value, size_t size) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.DataPackage.Hash)
}
inline ::std::string* DataPackage::mutable_hash() {
  
  // @@protoc_insertion_point(field_mutable:Core.DataPackage.Hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DataPackage::release_hash() {
  // @@protoc_insertion_point(field_release:Core.DataPackage.Hash)
  
  return hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DataPackage::set_allocated_hash(::std::string* hash) {
  if (hash != NULL) {
    
  } else {
    
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:Core.DataPackage.Hash)
}

// fixed64 Sender = 7;
inline void DataPackage::clear_sender() {
  sender_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DataPackage::sender() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Sender)
  return sender_;
}
inline void DataPackage::set_sender(::google::protobuf::uint64 value) {
  
  sender_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Sender)
}

// .Core.ResultType Result = 8;
inline void DataPackage::clear_result() {
  result_ = 0;
}
inline ::Core::ResultType DataPackage::result() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Result)
  return static_cast< ::Core::ResultType >(result_);
}
inline void DataPackage::set_result(::Core::ResultType value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:Core.DataPackage.Result)
}

// bytes Content = 9;
inline void DataPackage::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DataPackage::content() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Content)
  return content_.GetNoArena();
}
inline void DataPackage::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.DataPackage.Content)
}
#if LANG_CXX11
inline void DataPackage::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.DataPackage.Content)
}
#endif
inline void DataPackage::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.DataPackage.Content)
}
inline void DataPackage::set_content(const void* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.DataPackage.Content)
}
inline ::std::string* DataPackage::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:Core.DataPackage.Content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DataPackage::release_content() {
  // @@protoc_insertion_point(field_release:Core.DataPackage.Content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DataPackage::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:Core.DataPackage.Content)
}

// bytes Extend = 10;
inline void DataPackage::clear_extend() {
  extend_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DataPackage::extend() const {
  // @@protoc_insertion_point(field_get:Core.DataPackage.Extend)
  return extend_.GetNoArena();
}
inline void DataPackage::set_extend(const ::std::string& value) {
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.DataPackage.Extend)
}
#if LANG_CXX11
inline void DataPackage::set_extend(::std::string&& value) {
  
  extend_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.DataPackage.Extend)
}
#endif
inline void DataPackage::set_extend(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.DataPackage.Extend)
}
inline void DataPackage::set_extend(const void* value, size_t size) {
  
  extend_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.DataPackage.Extend)
}
inline ::std::string* DataPackage::mutable_extend() {
  
  // @@protoc_insertion_point(field_mutable:Core.DataPackage.Extend)
  return extend_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DataPackage::release_extend() {
  // @@protoc_insertion_point(field_release:Core.DataPackage.Extend)
  
  return extend_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DataPackage::set_allocated_extend(::std::string* extend) {
  if (extend != NULL) {
    
  } else {
    
  }
  extend_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extend);
  // @@protoc_insertion_point(field_set_allocated:Core.DataPackage.Extend)
}

// -------------------------------------------------------------------

// GLOBAL_CONFIG

// string ListenAddress = 1;
inline void GLOBAL_CONFIG::clear_listenaddress() {
  listenaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::listenaddress() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ListenAddress)
  return listenaddress_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_listenaddress(const ::std::string& value) {
  
  listenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ListenAddress)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_listenaddress(::std::string&& value) {
  
  listenaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ListenAddress)
}
#endif
inline void GLOBAL_CONFIG::set_listenaddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  listenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ListenAddress)
}
inline void GLOBAL_CONFIG::set_listenaddress(const char* value, size_t size) {
  
  listenaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ListenAddress)
}
inline ::std::string* GLOBAL_CONFIG::mutable_listenaddress() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ListenAddress)
  return listenaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_listenaddress() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ListenAddress)
  
  return listenaddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_listenaddress(::std::string* listenaddress) {
  if (listenaddress != NULL) {
    
  } else {
    
  }
  listenaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listenaddress);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ListenAddress)
}

// int32 ListenPort = 2;
inline void GLOBAL_CONFIG::clear_listenport() {
  listenport_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::listenport() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ListenPort)
  return listenport_;
}
inline void GLOBAL_CONFIG::set_listenport(::google::protobuf::int32 value) {
  
  listenport_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ListenPort)
}

// string LogPath = 3;
inline void GLOBAL_CONFIG::clear_logpath() {
  logpath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::logpath() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.LogPath)
  return logpath_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_logpath(const ::std::string& value) {
  
  logpath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.LogPath)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_logpath(::std::string&& value) {
  
  logpath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.LogPath)
}
#endif
inline void GLOBAL_CONFIG::set_logpath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  logpath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.LogPath)
}
inline void GLOBAL_CONFIG::set_logpath(const char* value, size_t size) {
  
  logpath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.LogPath)
}
inline ::std::string* GLOBAL_CONFIG::mutable_logpath() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.LogPath)
  return logpath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_logpath() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.LogPath)
  
  return logpath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_logpath(::std::string* logpath) {
  if (logpath != NULL) {
    
  } else {
    
  }
  logpath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logpath);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.LogPath)
}

// .Core.LogLevel LogLevel = 4;
inline void GLOBAL_CONFIG::clear_loglevel() {
  loglevel_ = 0;
}
inline ::Core::LogLevel GLOBAL_CONFIG::loglevel() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.LogLevel)
  return static_cast< ::Core::LogLevel >(loglevel_);
}
inline void GLOBAL_CONFIG::set_loglevel(::Core::LogLevel value) {
  
  loglevel_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.LogLevel)
}

// int32 LogOperation = 5;
inline void GLOBAL_CONFIG::clear_logoperation() {
  logoperation_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::logoperation() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.LogOperation)
  return logoperation_;
}
inline void GLOBAL_CONFIG::set_logoperation(::google::protobuf::int32 value) {
  
  logoperation_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.LogOperation)
}

// int32 MQThreadQuantity = 6;
inline void GLOBAL_CONFIG::clear_mqthreadquantity() {
  mqthreadquantity_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::mqthreadquantity() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.MQThreadQuantity)
  return mqthreadquantity_;
}
inline void GLOBAL_CONFIG::set_mqthreadquantity(::google::protobuf::int32 value) {
  
  mqthreadquantity_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.MQThreadQuantity)
}

// int32 EPollThreadQuantity = 7;
inline void GLOBAL_CONFIG::clear_epollthreadquantity() {
  epollthreadquantity_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::epollthreadquantity() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.EPollThreadQuantity)
  return epollthreadquantity_;
}
inline void GLOBAL_CONFIG::set_epollthreadquantity(::google::protobuf::int32 value) {
  
  epollthreadquantity_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.EPollThreadQuantity)
}

// int32 ProcessThreadQuantity = 8;
inline void GLOBAL_CONFIG::clear_processthreadquantity() {
  processthreadquantity_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::processthreadquantity() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ProcessThreadQuantity)
  return processthreadquantity_;
}
inline void GLOBAL_CONFIG::set_processthreadquantity(::google::protobuf::int32 value) {
  
  processthreadquantity_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ProcessThreadQuantity)
}

// int32 PrioritySize = 9;
inline void GLOBAL_CONFIG::clear_prioritysize() {
  prioritysize_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::prioritysize() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.PrioritySize)
  return prioritysize_;
}
inline void GLOBAL_CONFIG::set_prioritysize(::google::protobuf::int32 value) {
  
  prioritysize_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.PrioritySize)
}

// int32 ConnectTime = 10;
inline void GLOBAL_CONFIG::clear_connecttime() {
  connecttime_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::connecttime() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ConnectTime)
  return connecttime_;
}
inline void GLOBAL_CONFIG::set_connecttime(::google::protobuf::int32 value) {
  
  connecttime_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ConnectTime)
}

// int32 ReceiveTime = 11;
inline void GLOBAL_CONFIG::clear_receivetime() {
  receivetime_ = 0;
}
inline ::google::protobuf::int32 GLOBAL_CONFIG::receivetime() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ReceiveTime)
  return receivetime_;
}
inline void GLOBAL_CONFIG::set_receivetime(::google::protobuf::int32 value) {
  
  receivetime_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ReceiveTime)
}

// string ModuleName = 12;
inline void GLOBAL_CONFIG::clear_modulename() {
  modulename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::modulename() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ModuleName)
  return modulename_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_modulename(const ::std::string& value) {
  
  modulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ModuleName)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_modulename(::std::string&& value) {
  
  modulename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ModuleName)
}
#endif
inline void GLOBAL_CONFIG::set_modulename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  modulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ModuleName)
}
inline void GLOBAL_CONFIG::set_modulename(const char* value, size_t size) {
  
  modulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ModuleName)
}
inline ::std::string* GLOBAL_CONFIG::mutable_modulename() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ModuleName)
  return modulename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_modulename() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ModuleName)
  
  return modulename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_modulename(::std::string* modulename) {
  if (modulename != NULL) {
    
  } else {
    
  }
  modulename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), modulename);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ModuleName)
}

// string ModulePath = 13;
inline void GLOBAL_CONFIG::clear_modulepath() {
  modulepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::modulepath() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ModulePath)
  return modulepath_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_modulepath(const ::std::string& value) {
  
  modulepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ModulePath)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_modulepath(::std::string&& value) {
  
  modulepath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ModulePath)
}
#endif
inline void GLOBAL_CONFIG::set_modulepath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  modulepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ModulePath)
}
inline void GLOBAL_CONFIG::set_modulepath(const char* value, size_t size) {
  
  modulepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ModulePath)
}
inline ::std::string* GLOBAL_CONFIG::mutable_modulepath() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ModulePath)
  return modulepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_modulepath() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ModulePath)
  
  return modulepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_modulepath(::std::string* modulepath) {
  if (modulepath != NULL) {
    
  } else {
    
  }
  modulepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), modulepath);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ModulePath)
}

// bytes ModuleConfig = 14;
inline void GLOBAL_CONFIG::clear_moduleconfig() {
  moduleconfig_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::moduleconfig() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ModuleConfig)
  return moduleconfig_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_moduleconfig(const ::std::string& value) {
  
  moduleconfig_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ModuleConfig)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_moduleconfig(::std::string&& value) {
  
  moduleconfig_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ModuleConfig)
}
#endif
inline void GLOBAL_CONFIG::set_moduleconfig(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  moduleconfig_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ModuleConfig)
}
inline void GLOBAL_CONFIG::set_moduleconfig(const void* value, size_t size) {
  
  moduleconfig_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ModuleConfig)
}
inline ::std::string* GLOBAL_CONFIG::mutable_moduleconfig() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ModuleConfig)
  return moduleconfig_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_moduleconfig() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ModuleConfig)
  
  return moduleconfig_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_moduleconfig(::std::string* moduleconfig) {
  if (moduleconfig != NULL) {
    
  } else {
    
  }
  moduleconfig_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), moduleconfig);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ModuleConfig)
}

// string ModuleReference = 15;
inline void GLOBAL_CONFIG::clear_modulereference() {
  modulereference_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::modulereference() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ModuleReference)
  return modulereference_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_modulereference(const ::std::string& value) {
  
  modulereference_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ModuleReference)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_modulereference(::std::string&& value) {
  
  modulereference_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ModuleReference)
}
#endif
inline void GLOBAL_CONFIG::set_modulereference(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  modulereference_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ModuleReference)
}
inline void GLOBAL_CONFIG::set_modulereference(const char* value, size_t size) {
  
  modulereference_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ModuleReference)
}
inline ::std::string* GLOBAL_CONFIG::mutable_modulereference() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ModuleReference)
  return modulereference_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_modulereference() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ModuleReference)
  
  return modulereference_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_modulereference(::std::string* modulereference) {
  if (modulereference != NULL) {
    
  } else {
    
  }
  modulereference_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), modulereference);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ModuleReference)
}

// string ModuleFunctoins = 16;
inline void GLOBAL_CONFIG::clear_modulefunctoins() {
  modulefunctoins_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::modulefunctoins() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.ModuleFunctoins)
  return modulefunctoins_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_modulefunctoins(const ::std::string& value) {
  
  modulefunctoins_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.ModuleFunctoins)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_modulefunctoins(::std::string&& value) {
  
  modulefunctoins_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.ModuleFunctoins)
}
#endif
inline void GLOBAL_CONFIG::set_modulefunctoins(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  modulefunctoins_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.ModuleFunctoins)
}
inline void GLOBAL_CONFIG::set_modulefunctoins(const char* value, size_t size) {
  
  modulefunctoins_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.ModuleFunctoins)
}
inline ::std::string* GLOBAL_CONFIG::mutable_modulefunctoins() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.ModuleFunctoins)
  return modulefunctoins_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_modulefunctoins() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.ModuleFunctoins)
  
  return modulefunctoins_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_modulefunctoins(::std::string* modulefunctoins) {
  if (modulefunctoins != NULL) {
    
  } else {
    
  }
  modulefunctoins_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), modulefunctoins);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.ModuleFunctoins)
}

// bool EnableSSL = 17;
inline void GLOBAL_CONFIG::clear_enablessl() {
  enablessl_ = false;
}
inline bool GLOBAL_CONFIG::enablessl() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.EnableSSL)
  return enablessl_;
}
inline void GLOBAL_CONFIG::set_enablessl(bool value) {
  
  enablessl_ = value;
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.EnableSSL)
}

// string CertFilePath = 18;
inline void GLOBAL_CONFIG::clear_certfilepath() {
  certfilepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::certfilepath() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.CertFilePath)
  return certfilepath_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_certfilepath(const ::std::string& value) {
  
  certfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.CertFilePath)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_certfilepath(::std::string&& value) {
  
  certfilepath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.CertFilePath)
}
#endif
inline void GLOBAL_CONFIG::set_certfilepath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  certfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.CertFilePath)
}
inline void GLOBAL_CONFIG::set_certfilepath(const char* value, size_t size) {
  
  certfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.CertFilePath)
}
inline ::std::string* GLOBAL_CONFIG::mutable_certfilepath() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.CertFilePath)
  return certfilepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_certfilepath() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.CertFilePath)
  
  return certfilepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_certfilepath(::std::string* certfilepath) {
  if (certfilepath != NULL) {
    
  } else {
    
  }
  certfilepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), certfilepath);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.CertFilePath)
}

// string KeyFilePath = 19;
inline void GLOBAL_CONFIG::clear_keyfilepath() {
  keyfilepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::keyfilepath() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.KeyFilePath)
  return keyfilepath_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_keyfilepath(const ::std::string& value) {
  
  keyfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.KeyFilePath)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_keyfilepath(::std::string&& value) {
  
  keyfilepath_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.KeyFilePath)
}
#endif
inline void GLOBAL_CONFIG::set_keyfilepath(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  keyfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.KeyFilePath)
}
inline void GLOBAL_CONFIG::set_keyfilepath(const char* value, size_t size) {
  
  keyfilepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.KeyFilePath)
}
inline ::std::string* GLOBAL_CONFIG::mutable_keyfilepath() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.KeyFilePath)
  return keyfilepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_keyfilepath() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.KeyFilePath)
  
  return keyfilepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_keyfilepath(::std::string* keyfilepath) {
  if (keyfilepath != NULL) {
    
  } else {
    
  }
  keyfilepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), keyfilepath);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.KeyFilePath)
}

// string CertPasswd = 20;
inline void GLOBAL_CONFIG::clear_certpasswd() {
  certpasswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GLOBAL_CONFIG::certpasswd() const {
  // @@protoc_insertion_point(field_get:Core.GLOBAL_CONFIG.CertPasswd)
  return certpasswd_.GetNoArena();
}
inline void GLOBAL_CONFIG::set_certpasswd(const ::std::string& value) {
  
  certpasswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.GLOBAL_CONFIG.CertPasswd)
}
#if LANG_CXX11
inline void GLOBAL_CONFIG::set_certpasswd(::std::string&& value) {
  
  certpasswd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.GLOBAL_CONFIG.CertPasswd)
}
#endif
inline void GLOBAL_CONFIG::set_certpasswd(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  certpasswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.GLOBAL_CONFIG.CertPasswd)
}
inline void GLOBAL_CONFIG::set_certpasswd(const char* value, size_t size) {
  
  certpasswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.GLOBAL_CONFIG.CertPasswd)
}
inline ::std::string* GLOBAL_CONFIG::mutable_certpasswd() {
  
  // @@protoc_insertion_point(field_mutable:Core.GLOBAL_CONFIG.CertPasswd)
  return certpasswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GLOBAL_CONFIG::release_certpasswd() {
  // @@protoc_insertion_point(field_release:Core.GLOBAL_CONFIG.CertPasswd)
  
  return certpasswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GLOBAL_CONFIG::set_allocated_certpasswd(::std::string* certpasswd) {
  if (certpasswd != NULL) {
    
  } else {
    
  }
  certpasswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), certpasswd);
  // @@protoc_insertion_point(field_set_allocated:Core.GLOBAL_CONFIG.CertPasswd)
}

// -------------------------------------------------------------------

// RuntimeDataPackage

// string ManagerAddress = 1;
inline void RuntimeDataPackage::clear_manageraddress() {
  manageraddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RuntimeDataPackage::manageraddress() const {
  // @@protoc_insertion_point(field_get:Core.RuntimeDataPackage.ManagerAddress)
  return manageraddress_.GetNoArena();
}
inline void RuntimeDataPackage::set_manageraddress(const ::std::string& value) {
  
  manageraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Core.RuntimeDataPackage.ManagerAddress)
}
#if LANG_CXX11
inline void RuntimeDataPackage::set_manageraddress(::std::string&& value) {
  
  manageraddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Core.RuntimeDataPackage.ManagerAddress)
}
#endif
inline void RuntimeDataPackage::set_manageraddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  manageraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Core.RuntimeDataPackage.ManagerAddress)
}
inline void RuntimeDataPackage::set_manageraddress(const char* value, size_t size) {
  
  manageraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Core.RuntimeDataPackage.ManagerAddress)
}
inline ::std::string* RuntimeDataPackage::mutable_manageraddress() {
  
  // @@protoc_insertion_point(field_mutable:Core.RuntimeDataPackage.ManagerAddress)
  return manageraddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RuntimeDataPackage::release_manageraddress() {
  // @@protoc_insertion_point(field_release:Core.RuntimeDataPackage.ManagerAddress)
  
  return manageraddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RuntimeDataPackage::set_allocated_manageraddress(::std::string* manageraddress) {
  if (manageraddress != NULL) {
    
  } else {
    
  }
  manageraddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), manageraddress);
  // @@protoc_insertion_point(field_set_allocated:Core.RuntimeDataPackage.ManagerAddress)
}

// int32 ManagerPort = 2;
inline void RuntimeDataPackage::clear_managerport() {
  managerport_ = 0;
}
inline ::google::protobuf::int32 RuntimeDataPackage::managerport() const {
  // @@protoc_insertion_point(field_get:Core.RuntimeDataPackage.ManagerPort)
  return managerport_;
}
inline void RuntimeDataPackage::set_managerport(::google::protobuf::int32 value) {
  
  managerport_ = value;
  // @@protoc_insertion_point(field_set:Core.RuntimeDataPackage.ManagerPort)
}

// int32 TemplateID = 3;
inline void RuntimeDataPackage::clear_templateid() {
  templateid_ = 0;
}
inline ::google::protobuf::int32 RuntimeDataPackage::templateid() const {
  // @@protoc_insertion_point(field_get:Core.RuntimeDataPackage.TemplateID)
  return templateid_;
}
inline void RuntimeDataPackage::set_templateid(::google::protobuf::int32 value) {
  
  templateid_ = value;
  // @@protoc_insertion_point(field_set:Core.RuntimeDataPackage.TemplateID)
}

// fixed64 NodeUUID = 4;
inline void RuntimeDataPackage::clear_nodeuuid() {
  nodeuuid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RuntimeDataPackage::nodeuuid() const {
  // @@protoc_insertion_point(field_get:Core.RuntimeDataPackage.NodeUUID)
  return nodeuuid_;
}
inline void RuntimeDataPackage::set_nodeuuid(::google::protobuf::uint64 value) {
  
  nodeuuid_ = value;
  // @@protoc_insertion_point(field_set:Core.RuntimeDataPackage.NodeUUID)
}

// .Core.GLOBAL_CONFIG TemplateConfig = 5;
inline bool RuntimeDataPackage::has_templateconfig() const {
  return this != internal_default_instance() && templateconfig_ != NULL;
}
inline void RuntimeDataPackage::clear_templateconfig() {
  if (GetArenaNoVirtual() == NULL && templateconfig_ != NULL) {
    delete templateconfig_;
  }
  templateconfig_ = NULL;
}
inline const ::Core::GLOBAL_CONFIG& RuntimeDataPackage::_internal_templateconfig() const {
  return *templateconfig_;
}
inline const ::Core::GLOBAL_CONFIG& RuntimeDataPackage::templateconfig() const {
  const ::Core::GLOBAL_CONFIG* p = templateconfig_;
  // @@protoc_insertion_point(field_get:Core.RuntimeDataPackage.TemplateConfig)
  return p != NULL ? *p : *reinterpret_cast<const ::Core::GLOBAL_CONFIG*>(
      &::Core::_GLOBAL_CONFIG_default_instance_);
}
inline ::Core::GLOBAL_CONFIG* RuntimeDataPackage::release_templateconfig() {
  // @@protoc_insertion_point(field_release:Core.RuntimeDataPackage.TemplateConfig)
  
  ::Core::GLOBAL_CONFIG* temp = templateconfig_;
  templateconfig_ = NULL;
  return temp;
}
inline ::Core::GLOBAL_CONFIG* RuntimeDataPackage::mutable_templateconfig() {
  
  if (templateconfig_ == NULL) {
    auto* p = CreateMaybeMessage<::Core::GLOBAL_CONFIG>(GetArenaNoVirtual());
    templateconfig_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Core.RuntimeDataPackage.TemplateConfig)
  return templateconfig_;
}
inline void RuntimeDataPackage::set_allocated_templateconfig(::Core::GLOBAL_CONFIG* templateconfig) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete templateconfig_;
  }
  if (templateconfig) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      templateconfig = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, templateconfig, submessage_arena);
    }
    
  } else {
    
  }
  templateconfig_ = templateconfig;
  // @@protoc_insertion_point(field_set_allocated:Core.RuntimeDataPackage.TemplateConfig)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Core

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Core::DataPackage_PackageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::DataPackage_PackageType>() {
  return ::Core::DataPackage_PackageType_descriptor();
}
template <> struct is_proto_enum< ::Core::DataPackage_StatusType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::DataPackage_StatusType>() {
  return ::Core::DataPackage_StatusType_descriptor();
}
template <> struct is_proto_enum< ::Core::ResultType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::ResultType>() {
  return ::Core::ResultType_descriptor();
}
template <> struct is_proto_enum< ::Core::LogLevel> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::LogLevel>() {
  return ::Core::LogLevel_descriptor();
}
template <> struct is_proto_enum< ::Core::DATA_ITEM> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::DATA_ITEM>() {
  return ::Core::DATA_ITEM_descriptor();
}
template <> struct is_proto_enum< ::Core::EVENT_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::EVENT_TYPE>() {
  return ::Core::EVENT_TYPE_descriptor();
}
template <> struct is_proto_enum< ::Core::PRIORITY_LEVEL> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::PRIORITY_LEVEL>() {
  return ::Core::PRIORITY_LEVEL_descriptor();
}
template <> struct is_proto_enum< ::Core::ControlEvent> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Core::ControlEvent>() {
  return ::Core::ControlEvent_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_core_2eproto
