# Generated by Django 3.0 on 2019-12-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerList',
        ),
        migrations.DeleteModel(
            name='TagList',
        ),
    ]
