# Generated by Django 3.0 on 2019-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('notes', models.CharField(max_length=400)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('tag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('notes', models.CharField(max_length=40)),
            ],
        ),
    ]
